version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8089:8089"

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
